const portfolioImages = {
  smartData: [
    './img/portfolio/smart.jpg',
    './img/portfolio/smart1.jpg',
    './img/portfolio/smart2.jpg',
    './img/portfolio/smart3.jpg',
    './img/portfolio/smart4.jpg',
    './img/portfolio/smart5.jpg',
    './img/portfolio/smart6.jpg',
    './img/portfolio/smart7.jpg',
    './img/portfolio/smart8.jpg',
    './img/portfolio/smart9.jpg',
    './img/portfolio/smart10.jpg',
    './img/portfolio/smart11.jpg',
    './img/portfolio/smart12.jpg',
    './img/portfolio/smart13.jpg',
  ],
  ashleyData: [
    './img/portfolio/ashleymadison1.jpg',
    './img/portfolio/ashleymadison2.jpg',
    './img/portfolio/ashleymadison3.jpg',
    './img/portfolio/ashleymadison4.jpg',
    './img/portfolio/ashleymadison5.jpg',
    './img/portfolio/ashleymadison6.jpg',
    './img/portfolio/ashleymadison7.jpg',
    './img/portfolio/ashleymadison8.jpg',
    './img/portfolio/ashleymadison9.jpg',
  ],
  poledanceData: ['./img/portfolio/poledance1.jpg', './img/portfolio/poledance2.jpg', './img/portfolio/poledance3.jpg', './img/portfolio/poledance4.jpg'],
  producePlaceData: [
    './img/portfolio/produceplace1.jpg',
    './img/portfolio/produceplace2.jpg',
    './img/portfolio/produceplace3.jpg',
    './img/portfolio/produceplace4.jpg',
    './img/portfolio/produceplace5.jpg',
    './img/portfolio/produceplace6.jpg',
    './img/portfolio/produceplace7.jpg',
    './img/portfolio/produceplace8.jpg',
    './img/portfolio/produceplace9.jpg',
  ],
  innoceanData: [
    './img/portfolio/innocean1.jpg',
    './img/portfolio/innocean2.jpg',
    './img/portfolio/innocean3.jpg',
    './img/portfolio/innocean4.jpg',
    './img/portfolio/innocean5.jpg',
    './img/portfolio/innocean6.jpg',
    './img/portfolio/innocean7.jpg',
    './img/portfolio/innocean8.jpg',
    './img/portfolio/innocean9.jpg',
    './img/portfolio/innocean10.jpg',
  ],
  vpgData: ['./img/portfolio/vpg1.jpg', './img/portfolio/vpg2.jpg'],
  clotheslineData: ['./img/portfolio/clothesline.jpg', './img/portfolio/clothesline1.jpg', './img/portfolio/clothesline2.jpg'],
  ofgadminData: ['./img/portfolio/ofgadmin.jpg', './img/portfolio/ofgadmin1.jpg', './img/portfolio/ofgadmin2.jpg', './img/portfolio/ofgadmin3.jpg'],
  ofgsupplyData: [
    './img/portfolio/ofgsupply1.jpg',
    './img/portfolio/ofgsupply2.jpg',
    './img/portfolio/ofgsupply3.jpg',
    './img/portfolio/ofgsupply4.jpg',
    './img/portfolio/ofgsupply5.jpg',
    './img/portfolio/ofgsupply6.jpg',
  ],
  ofgData: ['./img/portfolio/ofg1.jpg', './img/portfolio/ofg2.jpg', './img/portfolio/ofg3.jpg', './img/portfolio/ofg4.jpg', './img/portfolio/ofg5.jpg', './img/portfolio/ofg6.jpg'],
  cfhiData: ['./img/portfolio/cfhi1.jpg', './img/portfolio/cfhi2.jpg', './img/portfolio/cfhi3.jpg', './img/portfolio/cfhi4.jpg'],
  monerisData: [
    './img/portfolio/moneris1.jpg',
    './img/portfolio/moneris2.jpg',
    './img/portfolio/moneris3.jpg',
    './img/portfolio/moneris4.jpg',
    './img/portfolio/moneris5.jpg',
    './img/portfolio/moneris6.jpg',
    './img/portfolio/moneris7.jpg',
  ],
  brandsinmotionData: [
    './img/portfolio/brandsinmotion1.jpg',
    './img/portfolio/brandsinmotion2.jpg',
    './img/portfolio/brandsinmotion3.jpg',
    './img/portfolio/brandsinmotion4.jpg',
    './img/portfolio/brandsinmotion5.jpg',
    './img/portfolio/brandsinmotion6.jpg',
    './img/portfolio/brandsinmotion7.jpg',
  ],
  letitsnowData: ['./img/portfolio/letitsnow1.jpg', './img/portfolio/letitsnow2.jpg', './img/portfolio/letitsnow3.jpg', './img/portfolio/letitsnow4.jpg'],
  focalPointData: ['./img/portfolio/focalpoint1.jpg', './img/portfolio/focalpoint2.jpg', './img/portfolio/focalpoint3.jpg', './img/portfolio/focalpoint4.jpg'],
  optimizer: ['./img/portfolio/optimizer.jpg'],
  harlequin: ['./img/portfolio/harlequin1.jpg'],
  crossword: ['./img/portfolio/crossword.jpg'],
  resourcemedia: ['./img/portfolio/resourcemedia.jpg'],
  amex: ['./img/portfolio/amex.jpg'],
  envy: ['./img/portfolio/envy.jpg'],
  bellworld: ['./img/portfolio/bellworld.jpg'],
}

export default portfolioImages
